<?php


namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CrudRepository ★コメントのクラス名を修正
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrudRepository extends EntityRepository ★クラス名を修正
{
    ★メソッドは一度全て削除
}
