<?php


namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorityRoleRepository ★リネーム
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorityRoleRepository extends EntityRepository ★リネーム
{

    /**
     * 権限、拒否URLでソートする
     *
     * @return array
     */
    public function findAllSort()
    {
        return $this->findBy(array(), array('Authority' => 'ASC', 'deny_url' => 'ASC'));
    }
}
